### ISSUE TITLE
non-portable path to file when build Linux Server on Windows

### ISSUE THREAD

**Issue by boskiv** [adamrehn/ue4cli#13] opened 2019-07-30 12:00 UTC
I have tried to package Linux build on Windows

```
ue4 setroot E:\UnrealEngine
ue4 package Development -noclient -server -serverplatform=Linux -platform=Linux
```

And got this error:
```
 [9/468] PCH.Engine.h
    E:/BuildAgentAccord/work/rnd_shooter_game/Intermediate/Build/Linux/B4D820EA/ShooterGameServer/Development/Engine/PCH.Engine.h(163,10):  error: non-portable path to file '"e\\UnrealEngine\Engine\Source\Runtime\Engine\Private\EnginePrivatePCH.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
    #include "e:\UnrealEngine\Engine\Source\Runtime\Engine\Private\EnginePrivatePCH.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             "e\\UnrealEngine\Engine\Source\Runtime\Engine\Private\EnginePrivatePCH.h"
```

```
 raise Exception('child process ' + str(command) + ' failed with exit code ' + str(returncode))
Exception: child process ['e:\\UnrealEngine\\Engine\\Build\\BatchFiles\\RunUAT.bat', 'BuildCookRun', '-utf8output', '-clientconfig=Development', '-serverconfig=Development', '-project=E:\\BuildAgentAccord\\work\\rnd_shooter_game\\ShooterGame.uproject', '-noP4', '-cook', '-build', '-stage', '-prereqs', '-pak', '-archive', '-archivedirectory=E:\\BuildAgentAccord\\work\\rnd_shooter_game\\dist', '-server', '-serverplatform=Linux', '-platform=Win64', '-allmaps'] failed with exit code 5
```

Any thoughts?

**Comment by adamrehn** [comment] 2019-08-03 05:32
The issue appears to be a mismatch between the generated header path and the actual filesystem path, based on the error output: `specified path differs in case from file name on disk `.

Are you sure `E:\UnrealEngine` is the exact casing of the Engine's root path, and it's not some other variation such as `E:\unrealengine`?

**Comment by sleeptightAnsiC** [comment] 2024-03-10 22:01
That's strange, OP used `-platform=Linux` flag but the subprocess was invoked with `-platform=Win64`, like if no `-platform` was specified at all. If I understand right, this should not happen. Here's the code that might be messing with it:
https://github.com/adamrehn/ue4cli/blob/39d6f6ab2aab1484d104850f2de8f8f8f3cf45cf/ue4cli/UnrealManagerBase.py#L398-L402

However, besides the wrong flag, the build failing wouldn't be an issue with ue4cli.
Even if the flag is wrong, the build should just go through or `RunUAT.bat` should yell about it.

**Comment by adamrehn** [comment] 2024-03-13 08:44
Hmmm, I've been unable to reproduce the behaviour where the `-platform` flag is set incorrectly when invoking RunUAT. Perhaps this was a bug that existed in an older version of ue4cli and was subsequently fixed, or was an oddity specific to the OP's environment.

In any case, @sleeptightAnsiC is correct in pointing out that the underlying error is a problem in AutomationTool itself, rather than an issue with ue4cli. On that basis, I'm going to close this, and if the strange `-platform` flag behaviour resurfaces then we can open a new issue to track that.

**Closed by adamrehn** 2024-03-13 08:44 UTC
